### ISSUE TITLE
About license

### ISSUE THREAD

**Issue by Eureka22** [Eureka22/agar-clone#23]
@m-byte Can I add a license to protect the additional part of the code (not the original one)? For example, if I want to put it under Apache license, or if I want everyone who use it provide a link to this repo?

What remind me of this idea is that I see some one running my client code for commercial use, even though I wrote the disclaimer in readme. I am afraid this will cause bad effect and cause loss for Zeach.

**Comment by m-byte** [comment]
Weird... I thought, I had answered this question. Somehow, my phone must not have sent it. Anyway:
As you can read at [the github page about licensing](https://help.github.com/articles/open-source-licensing/), if you don't pick any license, "you retain all rights to the software, except those outlined in the [GitHub Terms of Service](https://help.github.com/articles/github-terms-of-service/)".
The only relevant sentence there: "By setting your repositories to be viewed publicly, you agree to allow others to view and fork your repositories."

Putting the code under any license is actually more complicated than leaving it as is. This is due to the fact that you would have to get Zeach's permission to do so as part of the code is his.

Regarding the guys you don't want to use the code commercially: Just ask them to stop using any code under your copyright, and if you want to, also any code under my copyright. You have my permission to do so.

**Comment by Eureka22** [comment]
Thanks!
